quotes = ["You're barking up the wrong tree. I don't speak a word of Seolite, I've never met either one of my grandparents. And I've never *been* to Seol.\" He seems almost proud of these things. \"I'm a regular Revacholiere.",
    "Okay. I wanted to become an aerostatic pilot. Then I turned ten and realized we no longer have an air force.",
    "Binoclard... binoclard...\" he repeats to himself, eyes fixed on the ground.",
    "That time is over now.\" He looks at the pinball machine and breathes in. \"I was already a 38 year old man. It was unbecoming. As was playing pinball.",
    "Fine. I'm Kim 'Pinball' Kitsuragi.\" he puts them back on. \"AKA The Kimball. You remembered -- congratulations.",
    "I know this sounds fantastic. But I'm a four times decorated lieutenant of the RCM. I do not make up encounters with *cryptids* to spice up my day. I am very, very sane.",
    "I had a partner once. They called him Eyes, because he had to show me things. It's that bad.",
    "Hello, I'm Kim Kitsuragi.\" His grip is firm. \"Lieutenant, Precinct 57. You must be from the 41st...",
    "In my twenties I considered myself a moralist. *A blue forget-me-not, a piece of the sky*,\" he quotes. \"They're not all that bad.\" \"But the years have changed that. I don't know *what* I believe in now....\" He thinks, then changes his mind. \"No. I believe in the RCM. That's enough for me.",
    "Don't you *Welcome to Revachol* me,\" the lieutenant fires back. \"My grandfather came to here from a three-thousand-year-old racist-isolationist culture, while your ancestors came to this island a mere three hundred years ago.",
    "Every school of thought and government has failed in this city -- but I love it nonetheless. It belongs to me as much as it belongs to you.",
    "Unless we've veered off into a folded M dimension, I'm expecting to step out on the roof.",
    "Yes. And this 'mega-binoclard' knows how to sew a lapel and center a back vent.",
    "For real detective work, nothing beats a good notebook by your side...",
    "I apologize, but I only brought one with me. I have exactly one cigarette every night while going over my notes.",
    "I was born here. I grew up here. It's the only *home* I've ever known. And there's a good chance I'll die in the line of duty here, too.",
    "Agreed,\" the lieutenant chips in, \"pinball is the worst.",
    "It's a single-shot Kiejl A9. An *Armistice* to be precise.",
    "The lieutenant leans in. \"Hey, you promised you'd only ask about one cryptid.",
    "Ah, fuck it. Let's have more cryptids.",
    "Got any dope? We need some dope bad.\" He scratches his nose, then his armpit through the jacket. \"I got the *Boogie Street* shakes.",
    "Tryin'a score some *dope*, man. Tryin'a score some smack -- you got any?\" He hops from one foot to the other.",
    "The lieutenant leans in confidentially. \"You wouldn't be able to hear if he were wearing anal beads,\" he whispers.",
    "Dance?\" he repeats. \"*Monkey* fucker?",
    "I've heard people say *I* am on La Puta Madre's take.\" He looks you in the eye. \"And I am *not*.",
    "I do like to *hang around* the motor pool every now and then, but that doesn't make me a mechanic. Sort of like how hanging around the liquor store hasn't made you into a master distiller."
];
